version: '3'

networks:
    erlnet:
      driver: bridge
        #driver: bridge
        #ipam:
        #    driver: default
        #    config:
        #      - subnet: 172.16.238.0/24
              #gateway: "172.16.238.1"

services:
  erldock1:
    image: "erldock"
    networks:
      - erlnet
      #erlnet:
      #  ipv4_address: 172.16.238.10
  erldock2:
    image: "erldock"
    networks:
      - erlnet
      #erlnet:
      #  ipv4_address: 172.16.238.11
